---
sudo: required
dist: trusty
language: python
python:
  - "3.6"
addons:
  postgresql: "9.6"
git:
  depth: 3
install:
  - vagrant/install-on-travis-ci.sh
before_script:
  - psql -U postgres -c "create extension postgis"
  - cd $TRAVIS_BUILD_DIR/build
  - wget --no-verbose --output-document=../data/monaco.osm.pbf http://download.geofabrik.de/europe/monaco-latest.osm.pbf
  - ./utils/setup.php --osm-file ../data/monaco.osm.pbf --osm2pgsql-cache 1000 --all 2>&1 | grep -v 'ETA (seconds)'
script:
  - cd $TRAVIS_BUILD_DIR/test/php
  - phpunit ./
  - phpcs --report-width=120 */**.php
  - cd $TRAVIS_BUILD_DIR/test/bdd
  - # behave --format=progress3 api
  - behave --format=progress3 db
  - behave --format=progress3 osm2pgsql
notifications:
  email: false
